window.CALLEJERO = {
  "ADEJE": {
    "Autopista": [
      "Autopista del Sur"
    ],
    "Avenida": [
      "Avenida Adeje",
      "Avenida Adeje 300",
      "Avenida Alc. Walter Paetzmann",
      "Avenida Austria",
      "Avenida Ayyo",
      "Avenida Barranco de las Torres",
      "Avenida Barranco del Rey",
      "Avenida de Ayyo",
      "Avenida de Bruselas",
      "Avenida de Canarias",
      "Avenida de Colón",
      "Avenida de España",
      "Avenida de Europa",
      "Avenida de Francia",
      "Avenida de la Constitución",
      "Avenida de La Galga",
      "Avenida de la Macaronesia",
      "Avenida de las Gaviotas",
      "Avenida de los Acantilados",
      "Avenida de los Océanos",
      "Avenida de los Pueblos",
      "Avenida de los Vientos",
      "Avenida de Moscú",
      "Avenida de Palo Mayor",
      "Avenida del Poniente",
      "Avenida Ernesto Sarti",
      "Avenida Eugenio Domínguez Alfonso",
      "Avenida Eugenio Dominquez Alfonso",
      "Avenida Europa",
      "Avenida Francisco Ucelay Sabina",
      "Avenida Jardines del Duque",
      "Avenida Kurt Konrad Mayer",
      "Avenida Las Palmitas",
      "Avenida Playa Paraíso",
      "Avenida Quinto Centenario",
      "Avenida Rafael Puig Lluvina",
      "Avenida San Borondón",
      "Avenida Siam",
      "Avenida Tenerife",
      "Avenida V Centenario",
      "Avenida Viera y Clavijo",
      "Avenida Virgen de Guadalupe"
    ],
    "Calle": [
      "Barranco del Infierno",
      "Boca Cangrejo Alto",
      "Boca Cangrejo Bajo",
      "Boca del Paso-La Quinta",
      "Bodhi Trail",
      "Calle 30 de Mayo",
      "Calle Abinque",
      "Calle Abona",
      "Calle Acaymo",
      "Calle Agando",
      "Calle Agustina Espinosa",
      "Calle Ajabo",
      "Calle Alcojora",
      "Calle Alemania",
      "Calle Alfarroberos",
      "Calle Amantillo",
      "Calle Andalucía",
      "Calle Andorra",
      "Calle Antonio Machado",
      "Calle Aragón",
      "Calle Archajara",
      "Calle Argentina",
      "Calle Arigue",
      "Calle Asturias",
      "Calle Atalaya",
      "Calle Atbitocazpe",
      "Calle Atenas",
      "Calle Augustin Millares",
      "Calle Azimut",
      "Calle Bailén",
      "Calle Baleares",
      "Calle Barranco de las Moradas",
      "Calle Barranco del Inglés",
      "Calle Beirut",
      "Calle Beneharo",
      "Calle Bentinerfe",
      "Calle Berna",
      "Calle Bischofshofen",
      "Calle Bolivia",
      "Calle Bruselas",
      "Calle Cabo Verde",
      "Calle Camino de la Suerte Arriba",
      "Calle Canconaymo",
      "Calle Cantabria",
      "Calle Castilla",
      "Calle Castillo",
      "Calle Cataluña",
      "Calle Cercado el Pino",
      "Calle Ceuta",
      "Calle Chabú",
      "Calle Charfa",
      "Calle Chincanayro",
      "Calle Concepción García Álvarez",
      "Calle Corpus Cristi",
      "Calle Cuba",
      "Calle Daute",
      "Calle de Antonio Navarro",
      "Calle de la Galga",
      "Calle De La Laja",
      "Calle de la Paloma",
      "Calle de la Republica de Panama",
      "Calle de La Tosca",
      "Calle de la Zahorra",
      "Calle De Londres",
      "Calle de los Derechos Humanos",
      "Calle de Manuel Bello Ramos",
      "Calle de Noruega",
      "Calle de San Sebastián",
      "Calle de Tinerfe el Grande",
      "Calle del Carmen",
      "Calle del Mojón",
      "Calle del Tenique",
      "Calle del Valito",
      "Calle Diario de Avisos",
      "Calle Dinamarca",
      "Calle Doctor de las Casas Pérez",
      "Calle Dublin",
      "Calle Edmundo Esplugas",
      "Calle El Acebuche",
      "Calle El Aljibe",
      "Calle El Almendro",
      "Calle El Ancla",
      "Calle El Beril",
      "Calle El Brezo",
      "Calle El Cabezo",
      "Calle el Callao",
      "Calle El Cardón",
      "Calle El Cedro",
      "Calle El Cerco",
      "Calle El Drago",
      "Calle El Estanco Viejo",
      "Calle El Granero",
      "Calle El Horno",
      "Calle El Jable",
      "Calle El Laurel",
      "Calle el Mirador",
      "Calle El Monigal",
      "Calle El Morro",
      "Calle el Muelle",
      "Calle El Muelle",
      "Calle El Pedregal",
      "Calle El Peralillo",
      "Calle el Picón",
      "Calle El Pino",
      "Calle el Pinque",
      "Calle El Risco",
      "Calle El Sauce",
      "Calle El Viñatigo",
      "Calle Emeterio Gutiérrez Albelo",
      "Calle Era Grande",
      "Calle Eucalipto",
      "Calle Extremadura",
      "Calle Federico García Lorca",
      "Calle Félix Casanova de Ayala",
      "Calle Folías",
      "Calle Galicia",
      "Calle Gara",
      "Calle Gasparines",
      "Calle Girguín",
      "Calle Gondola",
      "Calle Gran Bretaña",
      "Calle Grande",
      "Calle Guanche",
      "Calle Guatemala",
      "Calle Guayarten",
      "Calle Guayeje",
      "Calle Guiguin",
      "Calle Gustavo Adolfo Becquer",
      "Calle Helsinki",
      "Calle Hermano Pedro",
      "Calle Hoyo del Roquito",
      "Calle Iboybo",
      "Calle Idafe",
      "Calle Irlanda",
      "Calle Isla de Alegranza",
      "Calle Isla de Fuerteventura",
      "Calle Isla de Gran Canaria",
      "Calle Isla de la Gomera",
      "Calle Isla de La Graciosa",
      "Calle Isla de la Palma",
      "Calle Isla de Lanzarote",
      "Calle Isla de Tenerife",
      "Calle Isla del Hierro",
      "Calle Islandia",
      "Calle Isora",
      "Calle Italia",
      "Calle Jardín Botánico",
      "Calle José Acosta",
      "Calle Josè Aguiar",
      "Calle Jose Espronceda",
      "Calle Juan Afonso Pláceres",
      "Calle La Arena",
      "Calle La Asomadita",
      "Calle La Borda",
      "Calle La Botavara",
      "Calle La Caleta",
      "Calle La Capellanía",
      "Calle La Cocineta",
      "Calle La Crucíta",
      "Calle la Cruz",
      "Calle La Cruz",
      "Calle La Curte Bajo",
      "Calle La Enramada",
      "Calle La Era",
      "Calle la Finquita",
      "Calle La Huerta",
      "Calle La Isa",
      "Calle la Lava",
      "Calle La Mesana",
      "Calle La Milagrosa",
      "Calle La Paz",
      "Calle La Pedrera",
      "Calle La Presa",
      "Calle La Retama",
      "Calle la Rioja",
      "Calle La Sabina",
      "Calle La Serrería",
      "Calle la Tabaiba",
      "Calle La Tablada",
      "Calle La Tosca",
      "Calle La Unión",
      "Calle La Vega",
      "Calle La Vera",
      "Calle la Viña",
      "Calle las Artes",
      "Calle Las Cañas",
      "Calle Las Jarcias",
      "Calle las Terrazas",
      "Calle León Felipe",
      "Calle Levante",
      "Calle Lisboa",
      "Calle Lomo del Caballo",
      "Calle Lomo del Clérigo",
      "Calle Lomo las Bellas",
      "Calle Lomo Morón",
      "Calle Lomo Morón Bajo",
      "Calle Londres",
      "Calle Los Andenes",
      "Calle Los Dámasos",
      "Calle Los Dáviles",
      "Calle Los Lomitos",
      "Calle Los Patameros",
      "Calle Luis Feria",
      "Calle Luján Pérez",
      "Calle Madrid",
      "Calle Malagueñas",
      "Calle Manos Unidas",
      "Calle Manuel Machado",
      "Calle Manuel Prieto Medina",
      "Calle Marruecos",
      "Calle Melilla",
      "Calle Mencey Bentor",
      "Calle Miguel de Cervantes",
      "Calle Miguel Hernández",
      "Calle Molinos",
      "Calle Montaña Clara",
      "Calle Morro Afonso",
      "Calle Morro Alfonso Alto",
      "Calle Morro de las Mesias",
      "Calle Morro Grueso",
      "Calle Murano",
      "Calle Murcia",
      "Calle Navarra",
      "Calle Neveda",
      "Calle Nivaria",
      "Calle Nueva",
      "Calle Paises Bajos",
      "Calle Paraguay",
      "Calle Paris",
      "Calle Pasos Largos",
      "Calle Patrona de Canarias",
      "Calle Pedro García Cabrera",
      "Calle Peligro",
      "Calle Pérez Galdós",
      "Calle Piedra Redonda",
      "Calle Playa de Diego Hernández",
      "Calle Poetas Canarios",
      "Calle Poetas Españoles",
      "Calle Ramón y Cajal",
      "Calle Reykjavik",
      "Calle Roma",
      "Calle Rombao Alto",
      "Calle Rombao Bajo",
      "Calle Roque de la Fortaleza",
      "Calle Roque de los Muchachos",
      "Calle Roque Nublo",
      "Calle Roques del Salmon",
      "Calle Rubén Darío",
      "Calle Rumén",
      "Calle Samarin",
      "Calle San Antonio",
      "Calle San Diego",
      "Calle San José",
      "Calle San Marcos",
      "Calle Santa Margarita",
      "Calle Secadero",
      "Calle Seguidilla",
      "Calle Sindicato",
      "Calle Tagara",
      "Calle Tagoror",
      "Calle Tajaraste",
      "Calle Tajinaste",
      "Calle Tajore",
      "Calle Taoro",
      "Calle Tegueste",
      "Calle Telefónica",
      "Calle Teowaldo Power",
      "Calle Terrero de los Pérez",
      "Calle Tierra Lavada",
      "Calle Tijoco",
      "Calle Tirso de Molina",
      "Calle Tomas Morales",
      "Calle Tórtola",
      "Calle Universidad de La Laguna",
      "Calle Unterhaching",
      "Calle Uruguay",
      "Calle Valencia",
      "Calle Varadero",
      "Calle Vardero",
      "Calle Venenchegue",
      "Calle Venezia",
      "Calle Venezuela",
      "Calle Verode",
      "Calle Virgen de Fátima",
      "Calle Virgen del Coromoto",
      "Callejón de los Frailes",
      "Llanos de Troya",
      "Lugar la Caldera",
      "Lugar Llano del Burro",
      "Lugar Pencatinta Bajo",
      "Montaña de las Lajas",
      "Pais Vasco",
      "Parque Sta. Úrsula",
      "Peatonal el Medregal",
      "Peatonal José Acosta",
      "Peatonal Los Abades",
      "Peatonal los Pescadores",
      "Plazoleta Riveira",
      "Pueblos Hermanos",
      "Puente Ajabo",
      "Roque del Conde",
      "The village"
    ],
    "Camino": [
      "Camino Carrasco",
      "Camino de Chacoroche",
      "Camino de Ifonche",
      "Camino de la Concepción",
      "Camino de la Curte",
      "Camino de la Virgen",
      "Camino de la Yegua de Don Tomás",
      "Camino de Las Moraditas",
      "Camino de las Rosas",
      "Camino de Los Picos",
      "Camino de Teresme",
      "Camino del Repicado",
      "Camino La Fuente El Chorrillo",
      "Camino Natural Anaga-Chasna",
      "Camino Real",
      "Camino Santana",
      "Camino Viejo de Adeje",
      "Camino Viejo de Taucho"
    ],
    "Carretera": [
      "Carretera acceso al Puertito",
      "Carretera General",
      "Carretera Los Menores-Taucho"
    ],
    "Pasaje": [
      "Pasaje Austria",
      "Pasaje Cabezos Sau"
    ],
    "Paseo": [
      "Paseo Barranco del Agua",
      "Paseo de la Pedrera",
      "Paseo de las Calmas",
      "paseo La Calleja",
      "Paseo La Lajita",
      "Paseo Las Palomas",
      "Paseo Maritimo",
      "Paseo Marítimo",
      "Paseo Maritmo",
      "Paseo Roque de la Fortaleza"
    ],
    "Plaza": [
      "Plaza César Manrique",
      "Plaza Charco del Valle",
      "Plaza de la Rosa",
      "Plaza de Venezuela",
      "Plaza de Venzuela",
      "Plaza del duque",
      "Plaza del Duque"
    ]
  },
  "ARONA": {
    "Autopista": [
      "Autopista del Sur"
    ],
    "Avenida": [
      "Avenida Antonio Dominguez",
      "Avenida Antonio Domínguez",
      "Avenida Arquitecto Gómez Cuesta",
      "Avenida Barranco del Rey",
      "Avenida Amsterdam",
      "Avenida Chayofita",
      "Avenida Juan Carlos I",
      "Avenida de la Constitución",
      "Avenida de Londres",
      "Avenida de los Pueblos",
      "Avenida Santiago Puig",
      "Avenida de Suecia",
      "Avenida del Arquitecto Gómez Cuesta",
      "Avenida del Atlántico",
      "Avenida El Palm-Mar",
      "Avenida Fernando Salazar González",
      "Avenida Fuerteventura",
      "Avenida Islas Canarias",
      "Avenida José Antonio Tavio",
      "Avenida Juan Alfonso Batista",
      "Avenida La Calma",
      "Avenida La Habana",
      "Avenida Las Americas",
      "Avenida los Playeros",
      "Avenida Los Playeros",
      "Avenida los Sabandeños",
      "Avenida Luciano Bello",
      "Avenida Marítima",
      "Avenida Principe Felipe",
      "Avenida Rafael Puig Lluvina",
      "Avenida San Francisco",
      "Avenida San Martín de Porres",
      "Avenida Siam",
      "Avenida Valle San Lorenzo"
    ],
    "Bulevar": [
      "Bulevar Chajofe"
    ],
    "Calle": [
      "Calle Abel",
      "Calle Abrigaño",
      "Calle Acapulco",
      "Calle Aceviño",
      "Calle Acirate",
      "Calle Acorán",
      "Calle Adán",
      "Calle Aderno",
      "Calle Adobe",
      "Calle Aganzo",
      "Calle Agreste",
      "Calle Aguijada",
      "Calle Alabastro",
      "Calle Albahaca",
      "Calle Albani",
      "Calle Albardón",
      "Calle Albariza",
      "Calle Albatros",
      "Calle Albedro",
      "Calle Alcorza",
      "Calle Aldaba",
      "Calle Alfareria",
      "Calle Algorín",
      "Calle Alhelí",
      "Calle Aljaba",
      "Calle Almácigo",
      "Calle Almadraba",
      "Calle Almorejo",
      "Calle Alojera",
      "Calle Amalía Alayón",
      "Calle Amarinta",
      "Calle Amatea",
      "Calle Amelga",
      "Calle Ana Vanesa",
      "Calle Andorra",
      "Calle Andrómeda",
      "Calle Antón Cojo",
      "Calle Antonio Bello",
      "Calle Apartadero",
      "Calle Aquiles",
      "Calle Arboleda",
      "Calle Arcilla",
      "Calle Areca",
      "Calle Arenales",
      "Calle Arenas Blancas",
      "Calle Argentina",
      "Calle Arguamul",
      "Calle Aries",
      "Calle Arkansas",
      "Calle Armiche",
      "Calle Armiño",
      "Calle Arrieta",
      "Calle Arure",
      "Calle Astrón",
      "Calle Asunción",
      "Calle Atenea",
      "Calle Atlas",
      "Calle Aurora",
      "Calle Austral",
      "Calle Baderna",
      "Calle Bahía del Galgo",
      "Calle Bajamar",
      "Calle Bajio",
      "Calle Balago",
      "Calle Balango",
      "Calle Balcón del Atlantico",
      "Calle Banano",
      "Calle Bandama",
      "Calle Barchimbre",
      "Calle Bari",
      "Calle Barranco del Verodal",
      "Calle Barranquera",
      "Calle Barranquillo",
      "Calle Barranquito",
      "Calle Barrio Nuevo",
      "Calle Barroso",
      "Calle Bejeque",
      "Calle Bejuco",
      "Calle Belén",
      "Calle Beleño",
      "Calle Bélgica",
      "Calle Bellavista",
      "Calle Belmaco",
      "Calle Benchijigua",
      "Calle Beneharo",
      "Calle Beña",
      "Calle Berenice",
      "Calle Bergantín",
      "Calle Berilo",
      "Calle Berna",
      "Calle Bogotá",
      "Calle Bolivia",
      "Calle Boneta",
      "Calle Boreal",
      "Calle Boreas",
      "Calle Boston",
      "Calle Bruma",
      "Calle Buenaventura Ordoñez",
      "Calle Buenaventura Ordóñez",
      "Calle Buenos Aires",
      "Calle Buril",
      "Calle Cabaña",
      "Calle Cabezón",
      "Calle Cabo de Abajo",
      "Calle Cabo del Balo",
      "Calle Cáceres",
      "Calle Cahice",
      "Calle Caín",
      "Calle Cairel",
      "Calle Cálamo",
      "Calle Caleta",
      "Calle Calicanto",
      "Calle California",
      "Calle Callao",
      "Calle Camaro",
      "Calle Cambra",
      "Calle Camelia",
      "Calle Cancajos",
      "Calle Cancela",
      "Calle Candela",
      "Calle Cándida Peña Bello",
      "Calle Candil",
      "Calle Cantería",
      "Calle Cañada Blanca",
      "Calle Caracas",
      "Calle Caramillo",
      "Calle Carmen Pérez Moya",
      "Calle Carozo",
      "Calle Casas Adentro",
      "Calle Casas de Abajo",
      "Calle Cascabel",
      "Calle Cascajo",
      "Calle Casiano Alfonso Hernández",
      "Calle Castaño",
      "Calle Cefeo",
      "Calle Cefiro",
      "Calle Celeste",
      "Calle Cellisca",
      "Calle Cementerio",
      "Calle Cénit",
      "Calle Centauro",
      "Calle Central",
      "Calle Cercado",
      "Calle Cercado Grande",
      "Calle Cerco del Pantago",
      "Calle Chacacharte",
      "Calle Chalana",
      "Calle Chasagua",
      "Calle Chasna",
      "Calle Chimbesque",
      "Calle Chindia",
      "Calle Choporro",
      "Calle Circunvalación",
      "Calle Colada",
      "Calle Collazo",
      "Calle Colombia",
      "Calle Compos",
      "Calle Concepción",
      "Calle Concepción Plasencia",
      "Calle Concreto",
      "Calle Constelación",
      "Calle Contreras",
      "Calle Cooperativa",
      "Calle Cornical",
      "Calle Coroma",
      "Calle Corona",
      "Calle Corta",
      "Calle Costa Rica",
      "Calle Cruz de San Antonio",
      "Calle Cruz del Guanche",
      "Calle Cumbre Nueva",
      "Calle Dante",
      "Calle de la Cruz",
      "Calle de la Iglesia",
      "Calle de la Té",
      "Calle de Víctor Zurita Soler",
      "Calle Dédalo",
      "Calle Del Centro",
      "Calle del Medio",
      "Calle del Valle Menéndez",
      "Calle Delta",
      "Calle Diana",
      "Calle Divina Pastora",
      "Calle Domínguez Alfonso",
      "Calle Dorada",
      "Calle Dornajo",
      "Calle Dr. Crespo",
      "Calle Dulce María Loinaz",
      "Calle Dulce María Loynaz",
      "Calle Duque de la Torre",
      "Calle Duquela",
      "Calle Ecuador",
      "Calle Edén",
      "Calle el Caletón",
      "Calle El Calvario",
      "Calle el Campo de Fútbol",
      "Calle el Cedro",
      "Calle el Cerco",
      "Calle el Chasnero",
      "Calle el Colegio",
      "Calle el Culantrillo",
      "Calle el Desierto",
      "Calle el Escobón",
      "Calle el Escobonal",
      "Calle el Fisco",
      "Calle El Fonil",
      "Calle El Hierro",
      "Calle el Hornillo",
      "Calle el Horno",
      "Calle el Llano",
      "Calle el Lomito",
      "Calle el Mago",
      "Calle el Majuelo",
      "Calle el Mojo",
      "Calle el Morro",
      "Calle el Mosquete",
      "Calle el Nido",
      "Calle El Parral",
      "Calle El Patio",
      "Calle el Percal",
      "Calle El Pilon",
      "Calle el Porís",
      "Calle El Ramal",
      "Calle el Roquito",
      "Calle el Rosal",
      "Calle el Salonito",
      "Calle el Sitio",
      "Calle El Terrero",
      "Calle El Toscal",
      "Calle el Varadero",
      "Calle Elvira",
      "Calle Emigrantes",
      "Calle Eneas",
      "Calle Envolvente",
      "Calle Era del Valo",
      "Calle Era las Mozas",
      "Calle Erbania",
      "Calle Eridano",
      "Calle Ernesto Castro Díaz",
      "Calle Escarpia",
      "Calle Espadal",
      "Calle Espigón del Benchijigua",
      "Calle Esquilón",
      "Calle Etesio",
      "Calle Eucaliptus",
      "Calle Faisán",
      "Calle Falúa",
      "Calle Famara",
      "Calle Fénix",
      "Calle Finca Toscal",
      "Calle Finlandia",
      "Calle Flor del Sur",
      "Calle Foque",
      "Calle Francisco de Miranda",
      "Calle Francisco Feo Rodríguez",
      "Calle Galera",
      "Calle Galga",
      "Calle Gamboa",
      "Calle Gandara",
      "Calle Garajonay",
      "Calle Garañaña",
      "Calle García Quintero",
      "Calle Garome",
      "Calle Gavilán",
      "Calle Gema",
      "Calle González del Yerro",
      "Calle Grama",
      "Calle Gran Canaria",
      "Calle Gran Rey",
      "Calle Guacimara",
      "Calle Guantánamo",
      "Calle Guargacho",
      "Calle Guayadeque",
      "Calle Guijarro",
      "Calle Hawai",
      "Calle Hawaii",
      "Calle Helechas",
      "Calle Herkules",
      "Calle Hermano Pedro",
      "Calle Hermano Pedro Bethencourt",
      "Calle Hermano Pedro de Bethencourt",
      "Calle Hespérides",
      "Calle Hipotenusa",
      "Calle Hornija",
      "Calle Ibarra",
      "Calle Ícaro",
      "Calle Igara",
      "Calle Ildefonso Bello",
      "Calle Imada",
      "Calle Infanta Cristina",
      "Calle Infanta Elena",
      "Calle Isla de la Gomera",
      "Calle Isla de la Palma",
      "Calle Isla de Lobos",
      "Calle Isla Margarita",
      "Calle Isla Verde",
      "Calle Izcagua",
      "Calle Jameos",
      "Calle Jandara",
      "Calle Jara",
      "Calle Jatoba",
      "Calle Jazmín",
      "Calle Jesús Domínguez Grillo",
      "Calle Jocama",
      "Calle Jorado",
      "Calle José del Roque",
      "Calle José García Allo",
      "Calle Jose María Galván Bello",
      "Calle Josefina Reverón",
      "Calle Juan Bariajo",
      "Calle Juan Carlos Darias",
      "Calle Juan Reverón Sierra",
      "Calle Juan XXIII",
      "Calle Juana González González",
      "Calle Junco",
      "Calle Junonia",
      "Calle Júpiter",
      "Calle la \"Z\"",
      "Calle la Arena",
      "Calle la Ballena",
      "Calle la Bloquera",
      "Calle La Bodega",
      "Calle la Cabezada",
      "Calle la Caldera",
      "Calle la Calera",
      "Calle la Campana",
      "Calle la Cerraja",
      "Calle la Colina",
      "Calle La Cotorra",
      "Calle la Degollada",
      "Calle la Dehesa",
      "Calle la Esperanza",
      "Calle La Flora",
      "Calle La Florida",
      "Calle la Fonda",
      "Calle la Gavia",
      "Calle la Goleta",
      "Calle la Gomera",
      "Calle La Graciosa",
      "Calle la Granja",
      "Calle la Hacienda",
      "Calle la Inmaculada",
      "Calle la Laderita",
      "Calle la Laguneta",
      "Calle la Leña",
      "Calle La Luna",
      "Calle la Luz",
      "Calle la Marina",
      "Calle la Montaña",
      "Calle la Montañita",
      "Calle la Morada",
      "Calle la Nuez",
      "Calle la Paloma",
      "Calle la Paz",
      "Calle la Peraza",
      "Calle la Perla",
      "Calle la Placita",
      "Calle la Punta",
      "Calle la Redonda",
      "Calle la Rosa",
      "Calle la Rosita",
      "Calle La Sabinita",
      "Calle La Tosca",
      "Calle la Trujilla",
      "Calle la Verada",
      "Calle La Victoria",
      "Calle Labrusca",
      "Calle Laderas del Espejo",
      "Calle Laderas del Teide",
      "Calle Lagar",
      "Calle Laguna Grande",
      "Calle Lampazo",
      "Calle Lanzarote",
      "Calle Larazulia",
      "Calle las Adelfas",
      "Calle las Cañadas",
      "Calle Las Casas",
      "Calle las Cuevas",
      "Calle las Flores",
      "Calle Las Fuentitas",
      "Calle las Gravas",
      "Calle las Lajas",
      "Calle las Maretas",
      "Calle las Rosas",
      "Calle las Varetas",
      "Calle las Vegas",
      "Calle Laurel",
      "Calle Laurisiva",
      "Calle Lavajo",
      "Calle Levante",
      "Calle Libertad",
      "Calle Lila",
      "Calle Lima",
      "Calle Limeta",
      "Calle Limón",
      "Calle Lisboa",
      "Calle Llano Mora",
      "Calle Llantén",
      "Calle Lobrego",
      "Calle Lola Fumero",
      "Calle Lomo de la Fuente",
      "Calle Lomo Negro",
      "Calle los Ángeles",
      "Calle Los Cardones",
      "Calle los Claveles",
      "Calle los Emigrantes",
      "Calle los Fundadores",
      "Calle los Geranios",
      "Calle los Leones",
      "Calle los Loros",
      "Calle Los Morales",
      "Calle los Naranjos",
      "Calle Los Pozos",
      "Calle los Riscos",
      "Calle los Rodríguez",
      "Calle los Salones",
      "Calle Lucila Barrios",
      "Calle Lucio Rodríguez Gómez",
      "Calle Lugano",
      "Calle Luis Álvarez Cruz",
      "Calle Luis Díaz de Losada",
      "Calle Magarza",
      "Calle Malpaís",
      "Calle Malva",
      "Calle Managua",
      "Calle Mancera",
      "Calle Manglar",
      "Calle Mantillo",
      "Calle Manuel Amant",
      "Calle Maocha",
      "Calle Maracaibo",
      "Calle Marea",
      "Calle María Consuelo Alfonso",
      "Calle María del Carmen García",
      "Calle María González López",
      "Calle María Rodríguez",
      "Calle Mata Gorda",
      "Calle Mazape",
      "Calle Meandro",
      "Calle Mejora",
      "Calle Mencey Acaymo",
      "Calle Mencey Bencomo",
      "Calle Meseta",
      "Calle México",
      "Calle Miguel Calcerrada",
      "Calle Mimbre",
      "Calle Minerva",
      "Calle Minos",
      "Calle Mirador la Cumbrita",
      "Calle Miramar",
      "Calle Mónaco",
      "Calle Monaga",
      "Calle Montana Amarilla",
      "Calle Montaña Caraba",
      "Calle Montaña Chamorga",
      "Calle Montaña Chica",
      "Calle Montaña Grande",
      "Calle Montaña Pardela",
      "Calle Montevideo",
      "Calle Morro Chayofa",
      "Calle Morro Cuba",
      "Calle Morro del Salón",
      "Calle Morro Lera",
      "Calle Mosquera",
      "Calle Mostaza",
      "Calle Nápoles",
      "Calle Neguilla",
      "Calle Nicaragua",
      "Calle Nicolás Pérez Escobar",
      "Calle Nivaria",
      "Calle Noelia Afonso Cabrera",
      "Calle Nordica",
      "Calle Norte",
      "Calle Noruega",
      "Calle Nuestra Señora de la Encarnación",
      "Calle Nueva",
      "Calle Nueva Explanada",
      "Calle Oasis",
      "Calle Obispo Antonio Tavira",
      "Calle Odisea",
      "Calle Ofiuco",
      "Calle Olimpia",
      "Calle Orchilla",
      "Calle Orégano",
      "Calle Oregón",
      "Calle Orilla",
      "Calle Orión",
      "Calle Orobal",
      "Calle Orotava",
      "Calle Órzola",
      "Calle Osa Mayor",
      "Calle Osa Menor",
      "Calle Otero",
      "Calle Pablos Abril",
      "Calle Palermo",
      "Calle Palmera",
      "Calle Palmito",
      "Calle Panadería",
      "Calle Panamá",
      "Calle Panizo",
      "Calle Paraguay",
      "Calle Paraiso Tropical",
      "Calle Paris",
      "Calle Parnasco",
      "Calle Pastoril",
      "Calle Patena",
      "Calle Pécora",
      "Calle Pedernal",
      "Calle Pedregales",
      "Calle Pensilvania",
      "Calle Perseo",
      "Calle Petalo",
      "Calle Piquera",
      "Calle Pizca",
      "Calle Playa Blanca",
      "Calle Polifemo",
      "Calle Portazgo",
      "Calle Princesa Dácil",
      "Calle Puerto Escondido",
      "Calle Puerto Rico",
      "Calle Punta Caballo",
      "Calle Punta Leona",
      "Calle Punta Negra",
      "Calle Punta Zalema",
      "Calle Quito",
      "Calle Rabera",
      "Calle Rafael Adrián",
      "Calle Ramón Pino",
      "Calle Ramujo",
      "Calle Rastrojo",
      "Calle Real",
      "Calle Real a Vento",
      "Calle Rebollo",
      "Calle Reina Sofía",
      "Calle Remolino",
      "Calle Revuelto",
      "Calle Ribazo",
      "Calle Risco Viceche",
      "Calle Rodeo",
      "Calle Romeral",
      "Calle Roque de Jama",
      "Calle Rosa Cabo",
      "Calle Rosaleda",
      "Calle Rosas del Guanche",
      "Calle Rubicón",
      "Calle Ruda",
      "Calle Sabinita Alta",
      "Calle Salicaria",
      "Calle Salinas del Faro",
      "Calle Salinas del Janubio",
      "Calle Salitre",
      "Calle Saloma",
      "Calle Salto del Chopo",
      "Calle Salvador González Alayón",
      "Calle Salvia",
      "Calle Samana",
      "Calle San Borondón",
      "Calle San Carlos Borromeo",
      "Calle San Casiano",
      "Calle San Claudio",
      "Calle San Clemente",
      "Calle San Diego",
      "Calle San Fernando",
      "Calle San Ismael",
      "Calle San Juan",
      "Calle San León",
      "Calle San Luis",
      "Calle San Miguel",
      "Calle San Roque",
      "Calle San Sebastián",
      "Calle San Sebastián de La Gomera",
      "Calle San Telmo",
      "Calle Sanjoras",
      "Calle Santa Ana",
      "Calle Santa Cruz de La Palma",
      "Calle Santa Elena",
      "Calle Santa Fe",
      "Calle Santa Isabel",
      "Calle Santa Rita",
      "Calle Santa Rosa",
      "Calle Santa Teresa",
      "Calle Santiago Fumero",
      "Calle Sargasa",
      "Calle Sargatillo",
      "Calle Sarmiento",
      "Calle Saturno",
      "Calle Sauce",
      "Calle Sésamo",
      "Calle Sierra Nevada",
      "Calle Siete Islas",
      "Calle Sindical",
      "Calle Sirio",
      "Calle Sol del Sur",
      "Calle Solana",
      "Calle Suárez",
      "Calle Suerte la",
      "Calle Tábano",
      "Calle Taburiente",
      "Calle Tagoror",
      "Calle Tahona",
      "Calle Tajadera",
      "Calle Tajaque",
      "Calle Tamargada",
      "Calle Taraja",
      "Calle Taroso",
      "Calle Tártago",
      "Calle Tasaigo",
      "Calle Tecina",
      "Calle Teguise",
      "Calle Telera",
      "Calle Ten-Bel",
      "Calle Tenerife",
      "Calle Texas",
      "Calle Tiberio",
      "Calle Tinaja",
      "Calle Tinerfe",
      "Calle Tinguafaya",
      "Calle Tinguaro",
      "Calle Tisana",
      "Calle Tonique",
      "Calle Tórtola",
      "Calle Toscal de los Herreros",
      "Calle Tostonera",
      "Calle Trainero",
      "Calle Trébol",
      "Calle Trebolina",
      "Calle Treinta de Mayo",
      "Calle Trinidad",
      "Calle Trocha",
      "Calle Trujillo",
      "Calle Tucán",
      "Calle Túnez",
      "Calle Turbión",
      "Calle Ulises",
      "Calle Uvero",
      "Calle Valle del Ahijadero",
      "Calle Valle Menéndez",
      "Calle Valparaiso",
      "Calle Varadero",
      "Calle Varejon",
      "Calle Venecia",
      "Calle Venezuela",
      "Calle Vento",
      "Calle Venus",
      "Calle Vera de Abajo",
      "Calle Vera de Arriba",
      "Calle Vera del Barranco",
      "Calle Verona",
      "Calle Vieja",
      "Calle Vilaflor",
      "Calle Villa Nazaret",
      "Calle Villa Vera",
      "Calle Villamar",
      "Calle Villarreal",
      "Calle Viranca",
      "Calle Virgen de Fatima",
      "Calle Virgen de Guadalupe",
      "Calle Virgen del Paso",
      "Calle Virgen del Pino",
      "Calle Virtud",
      "Calle Vista Martín",
      "Calle Zajari",
      "Calle Zanata",
      "Calle Zarcera",
      "Calle Zeus",
      "Calle Zodiaco",
      "Callejón Altea",
      "Callejón Ancelmas",
      "Callejón Andorga",
      "Callejon Antonio Alfonso Sierra",
      "Callejón Argoma",
      "Callejón Cabo de Arriba",
      "Callejón Cosco",
      "Callejón Dama",
      "Callejón de la Peñita",
      "Callejón Domínguez",
      "Callejón el Almendro",
      "Callejón el Canal",
      "Callejón el Hornito",
      "Callejón el Perú",
      "Callejón Emeterio",
      "Callejón Figón",
      "Callejón Galicia",
      "Callejón González",
      "Callejón Gonzalo",
      "Callejón Horno de la Teja",
      "Callejón Hoya del Toscal",
      "Callejón Jabeque",
      "Callejón Jaramago",
      "Callejón la Alforja",
      "Callejón la Cebada",
      "Callejón la Fajana",
      "Callejón la Peñita",
      "Callejón la Tronja",
      "Callejón las Avenas",
      "Callejón Leandra",
      "Callejón Lomito del Toscal",
      "Callejón los Asientos",
      "Callejón los Castilletes",
      "Callejón los Gemelos",
      "Callejón Luneta",
      "Callejón Méndez",
      "Callejón Mendoza",
      "Callejón Montemar",
      "Callejón Morga",
      "Callejón Odín",
      "Callejón Ollejo",
      "Callejón Picamolinos",
      "Callejón Quiteria",
      "Callejon Rocha",
      "Callejón Rombal",
      "Callejon Romin",
      "Callejón San Nicolás",
      "Callejón Solera",
      "Callejón Taray",
      "Callejón Tedera",
      "Callejón Témpano",
      "Callejón Tierra del Herrero",
      "Callejón Virgen Dolores",
      "Callejón Zabila",
      "Largo Pietro Vidale",
      "Las Tosqueras",
      "Las Vistas",
      "Llanos de Troya",
      "Pasillo de los Enanos",
      "Peatonal El Cabezo",
      "Peatonal Estocolmo",
    ],
    "Camino": [
      "Camino Albacora",
      "Camino Altavista",
      "Camino Ancora",
      "Camino Angostura",
      "Camino Arenado",
      "Camino Cañada Cho",
      "Camino Cañaveral",
      "Camino Cenacho",
      "Camino Chamorga",
      "Camino Charco Redondo",
      "Camino Chichia",
      "Camino Chimaca",
      "Camino Corvejón",
      "Camino de Coris",
      "Camino de la Capellanía",
      "Camino del Cazador",
      "Camino del Cercadito",
      "Camino del Roquete",
      "Camino el Lere",
      "Camino El Mojonito",
      "Camino el Pasil",
      "Camino el Resbaladero",
      "Camino el Roque",
      "Camino Fermin Reyes",
      "Camino Finca Caret",
      "Camino Finca Don Virgilio",
      "Camino Franciso Alfonso \"Güitima\"",
      "Camino Hoya de la Cruz",
      "Camino Hoya del Perro",
      "Camino La Balsa",
      "Camino la Fuente",
      "Camino La Guzmana",
      "Camino La Herradura",
      "Camino La Locera",
      "Camino La Longuera",
      "Camino la Saquera",
      "Camino la Zapatera",
      "Camino Laderas del Almacigo",
      "Camino Las Barbudas",
      "Camino las Cercas",
      "Camino Las Higueras",
      "Camino Las Hoyas",
      "Camino las Madrigueras",
      "Camino las Pardelitas",
      "Camino Las Tuneras",
      "Camino Llano de la Fuentita",
      "Camino Llano del Rey",
      "Camino Llano Vento",
      "Camino Lomo Corto",
      "Camino Lomo de las Hoyas",
      "Camino Los Balitos",
      "Camino los Castellanos",
      "Camino los Chijafes",
      "Camino los Migueles",
      "Camino Los Parlamentos",
      "Camino Los Vivitos",
      "Camino Luciano",
      "Camino Machín",
      "Camino Melgar",
      "Camino Montaña Chayofita",
      "Camino Morro las Acebedas",
      "Camino Morro Pinto",
      "Camino Natural Anaga-Chasna",
      "Camino Real",
      "Camino Real de Altavista",
      "Camino Real Llano Azul",
      "Camino Roque Vento",
      "Camino Roquete",
      "Camino Sta. Teresa Jornet Ibars",
      "Camino Tacoronte",
      "Camino Tagorito",
      "Camino Toscasur",
      "Camino Trocha Balitos",
      "Camino Viejo de Adeje"
    ],
    "Carretera": [
      "Carretera General Antigua",
      "Carretera General del Sur",
      "Carretera Sabinita - Llano Vento",
      "Ctra. General",
      "TF-66"
    ],
    "Pasaje": [
      "Pasaje Azucena"
    ],
    "Paseo": [
      "Paseo Achineche",
      "Paseo Alcaraván",
      "Paseo Amazonas",
      "Paseo Apolo",
      "Paseo Aquilino",
      "Paseo Berlín",
      "Paseo Burgado",
      "Paseo Cangrejo",
      "Paseo Chinyero",
      "Paseo Codorniz",
      "Paseo Cornisa",
      "Paseo Cristóbal Colón",
      "Paseo Cronos",
      "Paseo Cubesa",
      "Paseo Cuco",
      "Paseo Da...",
      "Paseo Del Marengo",
      "Paseo Dinamarca",
      "Paseo El Ancla",
      "Paseo El Cabezo",
      "Paseo el Ciclón",
      "Paseo El Dorado",
      "Paseo El Salinero",
      "Paseo Eloy García García",
      "Paseo Espigón Las Galletas",
      "Paseo Estocolmo",
      "Paseo Francisco Andrade Fumero",
      "Paseo Genova",
      "Paseo Guadalajara",
      "Paseo Iliade",
      "Paseo Jable",
      "Paseo Jorge Ledesma",
      "Paseo Jose Miguel",
      "Paseo las Mesas",
      "Paseo Las Piramides",
      "Paseo las Torres",
      "Paseo las Vistas",
      "Paseo Litoral",
      "Paseo Los Andes",
      "Paseo los Bolecos",
      "Paseo los Frailitos",
      "Paseo los Moritos",
      "Paseo Madrid",
      "Paseo María Amalia Frías",
      "Paseo Maritimo",
      "Paseo Marítimo",
      "Paseo Mocán",
      "Paseo Nicolás de Reverón",
      "Paseo Orinoco",
      "Paseo Pérez Valero",
      "Paseo Piconera",
      "Paseo Piteras",
      "Paseo Playa Graciosa",
      "Paseo Rincón del Puerto",
      "Paseo Roma",
      "Paseo Roque de Imoque",
      "Paseo Roque de los Brezos",
      "Paseo Roque del Conde",
      "Paseo San Salvador",
      "Paseo Santa Casilda",
      "Paseo Santa Cecilia",
      "Paseo Santa Eulalia",
      "Paseo Santa Julia",
      "Paseo Támesis",
      "Paseo Teide",
      "Paseo Tejuela",
      "Paseo Tenegua",
      "Paseo Teneguia",
      "Paseo Trasmallo",
      "Paseo Veracruz",
      "Paseo Verode"
    ],
    "Plaza": [
      "Plaza del Camisón",
      "Plaza la Fontana",
      "Plaza San Lorenzo",
      "Plaza Toronjil"
    ],
    "Rambla": [
      "Rambla Dionisio González"
    ]
  }
};