// countries.js
window.COUNTRIES_EN = {
  "AFGANISTAN": "Afghanistan",
  "ALBANIA": "Albania",
  "ALEMANIA": "Germany",
  "ANDORRA": "Andorra",
  "ANGOLA": "Angola",
  "ANTIGUA Y BARBUDA": "Antigua & Barbuda",
  "ARABIA SAUDI": "Saudi Arabia",
  "ARGELIA": "Algeria",
  "ARGENTINA": "Argentina",
  "ARMENIA": "Armenia",
  "AUSTRALIA": "Australia",
  "AUSTRIA": "Austria",
  "AZERBAIYAN": "Azerbaijan",
  "BAHAMAS": "Bahamas",
  "BAHREIN": "Bahrain",
  "BANGLADESH": "Bangladesh",
  "BARBADOS": "Barbados",
  "BELGICA": "Belgium",
  "BELICE": "Belize",
  "BENIN": "Benin",
  "BIELORRUSIA": "Belarus",
  "BOLIVIA": "Bolivia",
  "BOSNIA HERZEGOVINA": "Bosnia & Herzegovina",
  "BOSNIA Y HERZEGOVINA": "Bosnia & Herzegovina",
  "BOTSUANA": "Botswana",
  "BRASIL": "Brazil",
  "BRUNEI": "Brunei",
  "BULGARIA": "Bulgaria",
  "BURKINA FASO": "Burkina Faso",
  "BURUNDI": "Burundi",
  "BUTAN": "Bhutan",
  "CABO VERDE": "Cape Verde",
  "CAMBOYA": "Cambodia",
  "CAMERUN": "Cameroon",
  "CANADA": "Canada",
  "CATAR": "Qatar",
  "CHAD": "Chad",
  "CHILE": "Chile",
  "CHINA": "China",
  "CHIPRE": "Cyprus",
  "CIUDAD DEL VATICANO": "Vatican City",
  "COLOMBIA": "Colombia",
  "COMORAS": "Comoros",
  "CONGO": "Congo - Brazzaville",
  "COREA DEL NORTE": "North Korea",
  "COREA DEL SUR": "South Korea",
  "COSTA DE MARFIL": "Côte d’Ivoire",
  "COSTA RICA": "Costa Rica",
  "CROACIA": "Croatia",
  "CUBA": "Cuba",
  "DINAMARCA": "Denmark",
  "DOMINICA": "Dominica",
  "ECUADOR": "Ecuador",
  "EGIPTO": "Egypt",
  "EL SALVADOR": "El Salvador",
  "EMIRATOS ARABES UNIDOS": "United Arab Emirates",
  "ERITREA": "Eritrea",
  "ESLOVAQUIA": "Slovakia",
  "ESLOVENIA": "Slovenia",
  "ESPAÑA": "Spain",
  "ESTADOS UNIDOS": "United States",
  "ESTONIA": "Estonia",
  "ESUATINI": "Eswatini",
  "ETIOPIA": "Ethiopia",
  "FILIPINAS": "Philippines",
  "FINLANDIA": "Finland",
  "FIYI": "Fiji",
  "FRANCIA": "France",
  "GABON": "Gabon",
  "GAMBIA": "Gambia",
  "GEORGIA": "Georgia",
  "GHANA": "Ghana",
  "GRANADA": "Grenada",
  "GRECIA": "Greece",
  "GUATEMALA": "Guatemala",
  "GUINEA": "Guinea",
  "GUINEA BISSAU": "Guinea-Bissau",
  "GUINEA ECUATORIAL": "Equatorial Guinea",
  "GUYANA": "Guyana",
  "HAITI": "Haiti",
  "HONDURAS": "Honduras",
  "HUNGRIA": "Hungary",
  "INDIA": "India",
  "INDONESIA": "Indonesia",
  "IRAK": "Iraq",
  "IRAN": "Iran",
  "IRLANDA": "Ireland",
  "ISLANDIA": "Iceland",
  "ISLAS MARSHALL": "Marshall Islands",
  "ISLAS SALOMON": "Solomon Islands",
  "ISRAEL": "Israel",
  "ITALIA": "Italy",
  "JAMAICA": "Jamaica",
  "JAPON": "Japan",
  "JORDANIA": "Jordan",
  "KAZAJISTAN": "Kazakhstan",
  "KENIA": "Kenya",
  "KIRGUISTAN": "Kyrgyzstan",
  "KIRIBATI": "Kiribati",
  "KUWAIT": "Kuwait",
  "LAOS": "Laos",
  "LESOTO": "Lesotho",
  "LETONIA": "Latvia",
  "LIBANO": "Lebanon",
  "LIBERIA": "Liberia",
  "LIBIA": "Libya",
  "LIECHTENSTEIN": "Liechtenstein",
  "LITUANIA": "Lithuania",
  "LUXEMBURGO": "Luxembourg",
  "MADAGASCAR": "Madagascar",
  "MALASIA": "Malaysia",
  "MALAUI": "Malawi",
  "MALDIVAS": "Maldives",
  "MALI": "Mali",
  "MALTA": "Malta",
  "MARRUECOS": "Morocco",
  "MAURICIO": "Mauritius",
  "MAURITANIA": "Mauritania",
  "MEXICO": "Mexico",
  "MICRONESIA": "Micronesia",
  "MOLDAVIA": "Moldova",
  "MONACO": "Monaco",
  "MONGOLIA": "Mongolia",
  "MONTENEGRO": "Montenegro",
  "MOZAMBIQUE": "Mozambique",
  "MYANMAR": "Myanmar (Burma)",
  "NAMIBIA": "Namibia",
  "NAURU": "Nauru",
  "NEPAL": "Nepal",
  "NICARAGUA": "Nicaragua",
  "NIGER": "Niger",
  "NIGERIA": "Nigeria",
  "NORUEGA": "Norway",
  "NUEVA ZELANDA": "New Zealand",
  "OMAN": "Oman",
  "PAISES BAJOS": "Netherlands",
  "PAKISTAN": "Pakistan",
  "PALAOS": "Palau",
  "PANAMA": "Panama",
  "PAPUA NUEVA GUINEA": "Papua New Guinea",
  "PARAGUAY": "Paraguay",
  "PERU": "Peru",
  "POLONIA": "Poland",
  "PORTUGAL": "Portugal",
  "REINO UNIDO": "United Kingdom",
  "REPUBLICA CENTROAFRICANA": "Central African Republic",
  "REPUBLICA CHECA": "Czechia",
  "REPUBLICA DEL CONGO": "Congo - Kinshasa",
  "REPUBLICA DOMINICANA": "Dominican Republic",
  "RUANDA": "Rwanda",
  "RUMANIA": "Romania",
  "RUSIA": "Russia",
  "SAMOA": "Samoa",
  "SAN CRISTOBAL Y NIEVES": "St. Kitts & Nevis",
  "SAN MARINO": "San Marino",
  "SAN VICENTE Y LAS GRANADINAS": "St. Vincent & Grenadines",
  "SANTA LUCIA": "St. Lucia",
  "SANTO TOME Y PRINCIPE": "São Tomé & Príncipe",
  "SENEGAL": "Senegal",
  "SERBIA": "Serbia",
  "SEYCHELLES": "Seychelles",
  "SIERRA LEONA": "Sierra Leone",
  "SINGAPUR": "Singapore",
  "SIRIA": "Syria",
  "SOMALIA": "Somalia",
  "SRI LANKA": "Sri Lanka",
  "SUDAFRICA": "South Africa",
  "SUDAN": "Sudan",
  "SUDAN DEL SUR": "South Sudan",
  "SUECIA": "Sweden",
  "SUIZA": "Switzerland",
  "SURINAM": "Suriname",
  "TAILANDIA": "Thailand",
  "TANZANIA": "Tanzania",
  "TAYIKISTAN": "Tajikistan",
  "TIMOR ORIENTAL": "Timor-Leste",
  "TOGO": "Togo",
  "TONGA": "Tonga",
  "TRINIDAD Y TOBAGO": "Trinidad & Tobago",
  "TUNEZ": "Tunisia",
  "TURKMENISTAN": "Turkmenistan",
  "TURQUIA": "Türkiye",
  "TUVALU": "Tuvalu",
  "UCRANIA": "Ukraine",
  "UGANDA": "Uganda",
  "URUGUAY": "Uruguay",
  "UZBEKISTAN": "Uzbekistan",
  "VANUATU": "Vanuatu",
  "VENEZUELA": "Venezuela",
  "VIETNAM": "Vietnam",
  "YEMEN": "Yemen",
  "YIBUTI": "Djibouti",
  "ZAMBIA": "Zambia",
  "ZIMBABUE": "Zimbabwe",
  "DESCONOCIDO": "Unknown",
  "KOSOVO": "Kosovo",
"MACEDONIA DEL NORTE": "North Macedonia",
"REPUBLICA ESLOVACA": "Slovakia",

"ESTADOS UNIDOS AMERICA": "United States of America",

"DJIBOUTI": "Djibouti",
"REPUBLICA CONGO": "Republic of the Congo",
"REPUBLICA DEMOCRATICA CONGO": "Democratic Republic of the Congo",
"SAHARA": "Sahara",
"SAHARA OCCIDENTAL": "Western Sahara",

"AZERBAYAN": "Azerbaijan",
"BAREIN": "Bahrain",
"BIRMANIA": "Myanmar"
};
