window.PAISES = {
  "featured": ["ESPAÑA","DESCONOCIDO"],
  "groups": [
    {
      "label": "EUROPA",
      "items": [
        "ALBANIA","ALEMANIA","ANDORRA","AUSTRIA","BELGICA","BIELORRUSIA","BOSNIA HERZEGOVINA",
        "BULGARIA","CHIPRE","CROACIA","DINAMARCA","REPUBLICA ESLOVACA","ESLOVENIA","ESTONIA","FINLANDIA",
        "FRANCIA","GRECIA","HUNGRIA","IRLANDA","ISLANDIA","ITALIA","KOSOVO","LETONIA","LIECHTENSTEIN",
        "LITUANIA","LUXEMBURGO","MACEDONIA DEL NORTE","MALTA","MOLDAVIA","MONACO","MONTENEGRO",
        "NORUEGA","PAISES BAJOS","POLONIA","PORTUGAL","REINO UNIDO","REPUBLICA CHECA","RUMANIA",
        "RUSIA","SAN MARINO","SERBIA","SUECIA","SUIZA","UCRANIA","CIUDAD DEL VATICANO"
      ]
    },
    {
      "label": "AMÉRICA",
      "items": [
        "ANTIGUA Y BARBUDA","ARGENTINA","BAHAMAS","BARBADOS","BELICE","BOLIVIA","BRASIL","CANADA",
        "CHILE","COLOMBIA","COSTA RICA","CUBA","DOMINICA","ECUADOR","EL SALVADOR","ESTADOS UNIDOS AMERICA",
        "GRANADA","GUATEMALA","GUYANA","HAITI","HONDURAS","JAMAICA","MEXICO","NICARAGUA","PANAMA",
        "PARAGUAY","PERU","REPUBLICA DOMINICANA","SAN CRISTOBAL Y NIEVES","SAN VICENTE Y LAS GRANADINAS",
        "SANTA LUCIA","SURINAM","TRINIDAD Y TOBAGO","URUGUAY","VENEZUELA"
      ]
    },
    {
      "label": "ÁFRICA",
      "items": [
        "ARGELIA","ANGOLA","BENIN","BOTSUANA","BURKINA FASO","BURUNDI","CABO VERDE","CAMERUN",
        "CHAD","COMORAS","COSTA DE MARFIL","DJIBOUTI","EGIPTO","ERITREA","ESUATINI","ETIOPIA","GABON",
        "GAMBIA","GHANA","GUINEA","GUINEA BISSAU","GUINEA ECUATORIAL","KENIA","LESOTO","LIBERIA",
        "LIBIA","MADAGASCAR","MALAUI","MALI","MARRUECOS","MAURICIO","MAURITANIA","MOZAMBIQUE","NAMIBIA",
        "NIGER","NIGERIA","REPUBLICA CENTROAFRICANA","REPUBLICA CONGO","REPUBLICA DEMOCRATICA CONGO",
        "RUANDA","SANTO TOME Y PRINCIPE","SENEGAL","SEYCHELLES","SIERRA LEONA","SAHARA","SOMALIA","SUDAFRICA",
        "SUDAN","SUDAN DEL SUR","TANZANIA","TOGO","TUNEZ","UGANDA","ZAMBIA","ZIMBABUE","SAHARA OCCIDENTAL"
      ]
    },
    {
      "label": "ASIA",
      "items": [
        "AFGANISTAN","ARABIA SAUDI","ARMENIA","AZERBAYAN","BANGLADESH","BAREIN","BIRMANIA","BRUNEI",
        "BUTAN","CAMBOYA","CATAR","CHINA","COREA DEL NORTE","COREA DEL SUR","EMIRATOS ARABES UNIDOS",
        "FILIPINAS","GEORGIA","INDIA","INDONESIA","IRAK","IRAN","ISRAEL","JAPON","JORDANIA","KAZAJISTAN",
        "KIRGUISTAN","KUWAIT","LAOS","LIBANO","MALASIA","MALDIVAS","MONGOLIA","NEPAL","OMAN","PAKISTAN",
        "RUSIA","SINGAPUR","SIRIA","SRI LANKA","TAYIKISTAN","TAILANDIA","TIMOR ORIENTAL","TURKMENISTAN",
        "TURQUIA","UZBEKISTAN","VIETNAM","YEMEN"
      ]
    },
    {
      "label": "OCEANÍA",
      "items": [
        "AUSTRALIA","FIYI","ISLAS MARSHALL","ISLAS SALOMON","KIRIBATI","MICRONESIA",
        "NAURU","NUEVA ZELANDA","PALAOS","PAPUA NUEVA GUINEA","SAMOA","TONGA","TUVALU","VANUATU"
      ]
    }
  ]
};