window.PROVINCIAS_ES = [
  "SANTA CRUZ DE TENERIFE",
  "LA CORUÑA","ALAVA","ALBACETE","ALICANTE","ALMERIA","ASTURIAS","AVILA","BADAJOZ",
  "BALEARES","BARCELONA","BURGOS","CACERES","CADIZ","CANTABRIA","CASTELLON/CASTELLO",
  "CIUDAD REAL","CORDOBA","CUENCA","GIRONA","GRANADA","GUADALAJARA","GUIPUZCOA",
  "HUELVA","HUESCA","JAEN","LA RIOJA","LAS PALMAS","LEON","LLEIDA","LUGO","MADRID",
  "MALAGA","MURCIA","NAVARRA","ORENSE","PALENCIA","PONTEVEDRA","SALAMANCA","SEGOVIA",
  "SEVILLA","SORIA","TARRAGONA","TERUEL","TOLEDO","VALENCIA","VALLADOLID","VIZCAYA",
  "ZAMORA","ZARAGOZA","CEUTA","MELILLA","-"
];